#pragma once

enum DBKey
{
	DB_COP_HEAT = 32,
	DB_COP_HEAT_MAX,
	DB_GANG_HEAT,
	DB_GANG_HEAT_MAX,
	DB_SNIPER_ZOOM = 43,
	DB_SNIPER_ZOOM_MAX,
	DB_REPUTATION_LEVEL = 86,
	DB_STAT_HEAD_SHOTS = 103,
	DB_STAT_LEFT_NUT_SHOTS,
	DB_STAT_RIGHT_NUT_SHOTS,
	DB_STAT_GROIN_SHOTS,
	DB_STAT_KIDNEY_SHOTS,
	DB_STAT_ARM_SHOTS,
	DB_STAT_LEG_SHOTS,
	DB_PLAYER_IN_RAGE = 121,
	DB_PLAYER_IN_SNIPER_MODE,
	DB_CURRENT_HUD_IMAGE = 148,
	DB_EVENT_RENDERFX = 207,
	DB_EVENT_SHOW_HUD_IMAGE = 214,
	DB_INVALID_ENTRY = 228,
};