#pragma once

namespace pure3d
{
    enum pddiCompareMode
    {
        PDDI_COMPARE_NONE,
        PDDI_COMPARE_ALWAYS,
        PDDI_COMPARE_LESS,
        PDDI_COMPARE_LESSEQUAL,
        PDDI_COMPARE_GREATER,
        PDDI_COMPARE_GREATEREQUAL,
        PDDI_COMPARE_EQUAL,
        PDDI_COMPARE_NOTEQUAL
    };

    enum pddiCullMode
    {
        PDDI_CULL_NONE,
        PDDI_CULL_NORMAL,
        PDDI_CULL_INVERTED,
        PDDI_CULL_SHADOW_BACKFACE,
        PDDI_CULL_SHADOW_FRONTFACE
    };

    enum pddiDisplayMode
    {
        PDDI_DISPLAY_FULLSCREEN,
        PDDI_DISPLAY_WINDOW,
        PDDI_DISPLAY_FULLSCREEN_PAL
    };

    enum pddiFillMode
    {
        PDDI_FILL_SOLID,
        PDDI_FILL_WIRE,
        PDDI_FILL_POINT
    };

    enum pddiProjectionMode
    {
        PDDI_PROJECTION_PERSPECTIVE,
        PDDI_PROJECTION_ORTHOGRAPHIC,
        PDDI_PROJECTION_DEVICE
    };

    enum pddiStatType
    {
        PDDI_STAT_CURRENT_FRAME,
        PDDI_STAT_FRAME_TIME,
        PDDI_STAT_BUFFERED_PRIM,
        PDDI_STAT_BUFFERED_PRIM_VERT,
        PDDI_STAT_BUFFERED_INDEXED_PRIM,
        PDDI_STAT_BUFFERED_INDEXED_PRIM_VERT,
        PDDI_STAT_BUFFERED_PRIM_CALLS,
        PDDI_STAT_BUFFERED_PRIM_AVG,
        PDDI_STAT_BUFFERED_COUNT,
        PDDI_STAT_BUFFERED_ALLOC,
        PDDI_STAT_STREAMED_PRIM,
        PDDI_STAT_STREAMED_PRIM_VERT,
        PDDI_STAT_STREAMED_PRIM_CALLS,
        PDDI_STAT_STREAMED_PRIM_AVG,
        PDDI_STAT_SKINNED_BONES,
        PDDI_STAT_SKINNED_XFORM_VERT,
        PDDI_STAT_SKINNED_XFORM_MS,
        PDDI_STAT_SKINNED_WAIT_MS,
        PDDI_STAT_MATRIX_OPS,
        PDDI_STAT_LIGHT_OPS,
        PDDI_STAT_MATERIAL_OPS,
        PDDI_STAT_TEXTURE_HITS,
        PDDI_STAT_TEXTURE_MISSES,
        PDDI_STAT_TEXTURE_UPLOADED,
        PDDI_STAT_TEXTURE_ALLOCATED,
        PDDI_STAT_TEXTURE_SLOP,
        PDDI_STAT_TEXTURE_COUNT_4BIT,
        PDDI_STAT_TEXTURE_ALLOC_4BIT,
        PDDI_STAT_TEXTURE_COUNT_8BIT,
        PDDI_STAT_TEXTURE_ALLOC_8BIT,
        PDDI_STAT_TEXTURE_COUNT_16BIT,
        PDDI_STAT_TEXTURE_ALLOC_16BIT,
        PDDI_STAT_TEXTURE_COUNT_32BIT,
        PDDI_STAT_TEXTURE_ALLOC_32BIT,
        PDDI_STAT_TEXTURE_COUNT_DXTN,
        PDDI_STAT_TEXTURE_ALLOC_DXTN
    };
}